/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProRouteImport } from './routes/pro'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as EntreprisesRouteImport } from './routes/entreprises'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkerWorkerIdRouteImport } from './routes/worker.$workerId'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileCompleteRouteImport } from './routes/profile.complete'
import { Route as NotificationsNotifIdRouteImport } from './routes/notifications.$notifId'
import { Route as CompanyCompanyIdRouteImport } from './routes/company.$companyId'

const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreprisesRoute = EntreprisesRouteImport.update({
  id: '/entreprises',
  path: '/entreprises',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerWorkerIdRoute = WorkerWorkerIdRouteImport.update({
  id: '/worker/$workerId',
  path: '/worker/$workerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileCompleteRoute = ProfileCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => ProfileRoute,
} as any)
const NotificationsNotifIdRoute = NotificationsNotifIdRouteImport.update({
  id: '/$notifId',
  path: '/$notifId',
  getParentRoute: () => NotificationsRoute,
} as any)
const CompanyCompanyIdRoute = CompanyCompanyIdRouteImport.update({
  id: '/company/$companyId',
  path: '/company/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/entreprises': typeof EntreprisesRoute
  '/favorites': typeof FavoritesRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
  '/notifications/$notifId': typeof NotificationsNotifIdRoute
  '/profile/complete': typeof ProfileCompleteRoute
  '/profile/edit': typeof ProfileEditRoute
  '/worker/$workerId': typeof WorkerWorkerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/entreprises': typeof EntreprisesRoute
  '/favorites': typeof FavoritesRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
  '/notifications/$notifId': typeof NotificationsNotifIdRoute
  '/profile/complete': typeof ProfileCompleteRoute
  '/profile/edit': typeof ProfileEditRoute
  '/worker/$workerId': typeof WorkerWorkerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/entreprises': typeof EntreprisesRoute
  '/favorites': typeof FavoritesRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
  '/notifications/$notifId': typeof NotificationsNotifIdRoute
  '/profile/complete': typeof ProfileCompleteRoute
  '/profile/edit': typeof ProfileEditRoute
  '/worker/$workerId': typeof WorkerWorkerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/entreprises'
    | '/favorites'
    | '/language'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/pro'
    | '/profile'
    | '/reviews'
    | '/company/$companyId'
    | '/notifications/$notifId'
    | '/profile/complete'
    | '/profile/edit'
    | '/worker/$workerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/entreprises'
    | '/favorites'
    | '/language'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/pro'
    | '/profile'
    | '/reviews'
    | '/company/$companyId'
    | '/notifications/$notifId'
    | '/profile/complete'
    | '/profile/edit'
    | '/worker/$workerId'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/entreprises'
    | '/favorites'
    | '/language'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/pro'
    | '/profile'
    | '/reviews'
    | '/company/$companyId'
    | '/notifications/$notifId'
    | '/profile/complete'
    | '/profile/edit'
    | '/worker/$workerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  EntreprisesRoute: typeof EntreprisesRoute
  FavoritesRoute: typeof FavoritesRoute
  LanguageRoute: typeof LanguageRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProRoute: typeof ProRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ReviewsRoute: typeof ReviewsRoute
  CompanyCompanyIdRoute: typeof CompanyCompanyIdRoute
  WorkerWorkerIdRoute: typeof WorkerWorkerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprises': {
      id: '/entreprises'
      path: '/entreprises'
      fullPath: '/entreprises'
      preLoaderRoute: typeof EntreprisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/$workerId': {
      id: '/worker/$workerId'
      path: '/worker/$workerId'
      fullPath: '/worker/$workerId'
      preLoaderRoute: typeof WorkerWorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/complete': {
      id: '/profile/complete'
      path: '/complete'
      fullPath: '/profile/complete'
      preLoaderRoute: typeof ProfileCompleteRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/notifications/$notifId': {
      id: '/notifications/$notifId'
      path: '/$notifId'
      fullPath: '/notifications/$notifId'
      preLoaderRoute: typeof NotificationsNotifIdRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/company/$companyId': {
      id: '/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/company/$companyId'
      preLoaderRoute: typeof CompanyCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NotificationsRouteChildren {
  NotificationsNotifIdRoute: typeof NotificationsNotifIdRoute
}

const NotificationsRouteChildren: NotificationsRouteChildren = {
  NotificationsNotifIdRoute: NotificationsNotifIdRoute,
}

const NotificationsRouteWithChildren = NotificationsRoute._addFileChildren(
  NotificationsRouteChildren,
)

interface ProfileRouteChildren {
  ProfileCompleteRoute: typeof ProfileCompleteRoute
  ProfileEditRoute: typeof ProfileEditRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileCompleteRoute: ProfileCompleteRoute,
  ProfileEditRoute: ProfileEditRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  EntreprisesRoute: EntreprisesRoute,
  FavoritesRoute: FavoritesRoute,
  LanguageRoute: LanguageRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProRoute: ProRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ReviewsRoute: ReviewsRoute,
  CompanyCompanyIdRoute: CompanyCompanyIdRoute,
  WorkerWorkerIdRoute: WorkerWorkerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

